"""Add shipping info to orders

Revision ID: 8282c5ad43d5
Revises: be95a1d5e8b3
Create Date: 2025-01-09 18:09:46.259840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8282c5ad43d5'
down_revision = 'be95a1d5e8b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('shipping_address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('shipping_address')
        batch_op.drop_column('shipping_name')

    # ### end Alembic commands ###
