"""Add shipping info to orders

Revision ID: be95a1d5e8b3
Revises: ab6411d2083d
Create Date: 2025-01-09 18:08:07.372361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be95a1d5e8b3'
down_revision = 'ab6411d2083d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_purchase')
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('_alembic_tmp_purchase',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('part_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('total_price', sa.FLOAT(), nullable=False),
    sa.Column('purchase_date', sa.DATETIME(), nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['part.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
